package sistemaescolar;

import com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme;
import java.awt.Color;
import java.awt.Image;
import javadb.consultasSQL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class VentanaLogin extends javax.swing.JFrame implements iniciarInstanciaEstudiante, iniciarInstanciaProfesor {

    VentanaRegistroSeleccion registro = new VentanaRegistroSeleccion();
    consultasSQL consulta = new consultasSQL();

    //debug mostrar ventanaLogin
    private static boolean loginVisible = true;

    //booleano selecciona rol
    private boolean comprobarRol = false;

    public VentanaLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Colegio San José - Inicio");
        Image icono = new ImageIcon(getClass().getResource("/img/icono.png")).getImage();
        setIconImage(icono);
        //estudiante.setVisible(true);
        //profesor.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelDatosSuperior = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        labelTitulo = new javax.swing.JLabel();
        botonLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        clickRegister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(51, 0, 51));

        panelDatosSuperior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        panelDatosSuperior.setOpaque(false);

        panelDatos.setBackground(new java.awt.Color(102, 0, 103));
        panelDatos.setFocusTraversalPolicyProvider(true);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");

        fieldUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N

        fieldPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Inicio sesión del Colegio");

        botonLogin.setBackground(new java.awt.Color(102, 0, 255));
        botonLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        botonLogin.setForeground(new java.awt.Color(255, 255, 255));
        botonLogin.setText("Iniciar sesión");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelTitulo)
                .addGap(15, 15, 15)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(botonLogin)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout panelDatosSuperiorLayout = new javax.swing.GroupLayout(panelDatosSuperior);
        panelDatosSuperior.setLayout(panelDatosSuperiorLayout);
        panelDatosSuperiorLayout.setHorizontalGroup(
            panelDatosSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDatosSuperiorLayout.setVerticalGroup(
            panelDatosSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¿No tienes una cuenta?");

        clickRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clickRegister.setForeground(new java.awt.Color(255, 255, 255));
        clickRegister.setText("<HTML><U>Regístrate</U></HTML>");
        clickRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clickRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clickRegisterMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clickRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelDatosSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clickRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickRegisterMouseClicked
        this.dispose();
        registro.setVisible(true);
    }//GEN-LAST:event_clickRegisterMouseClicked

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        comprobacionCampos();
        if (comprobarRol) {
            validarRol();
        }
    }//GEN-LAST:event_botonLoginActionPerformed

    private void clickRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickRegisterMouseEntered
        clickRegister.setForeground(new Color(0, 51, 253));
        clickRegister.setText("<HTML><U>Regístrate</U></HTML>");
    }//GEN-LAST:event_clickRegisterMouseEntered

    private void clickRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickRegisterMouseExited
        clickRegister.setForeground(Color.white);
        clickRegister.setText("<HTML><U>Regístrate</U></HTML>");
    }//GEN-LAST:event_clickRegisterMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new FlatDarkPurpleIJTheme());

        } catch (UnsupportedLookAndFeelException ex) {
            System.exit(0);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(loginVisible);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLogin;
    private javax.swing.JLabel clickRegister;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelDatosSuperior;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables

    private void comprobacionCampos() {
        String usuario = fieldUsuario.getText();
        String password = String.valueOf(fieldPassword.getPassword());
        if (usuario.isBlank() || password.isBlank()) {
            comprobarRol = false;
            JOptionPane.showMessageDialog(null, "ERROR: Los campos están vacios", "ERROR", 0);
        } else {
            consulta.guardarUsuario(usuario);
            consulta.guardarClave(password);
            comprobarRol = true;
        }
    }

    private void validarRol() {
        String usuario = fieldUsuario.getText();
        String rol = consulta.comprobarRol();
        switch (rol) {
            case "Estudiante":
                consulta.loginEstudiante();
                if (consulta.credencialesValidas()) {
                    consulta.guardarUsuario(usuario);
                    enviarNombreEstudiante();
                    enviarCurso();
                    consulta.mostrarDatosEstudianteLogin();
                    mostrarVentanaEstudiante(true);
                    this.dispose();
                }
                break;
            case "Profesor":
                consulta.loginProfesor();
                if (consulta.credencialesValidas()) {
                    consulta.guardarUsuario(usuario);
                    enviarDatosProfesor();
                    consulta.mostrarDatosProfesorLogin();
                    mostrarVentanaProfesor(true);
                    this.dispose();
                }
                break;
            case "No tiene rol":
                JOptionPane.showMessageDialog(null, "ERROR: El usuario ingresado no existe", "ERROR", 0);
                break;
            default:
                break;
        }
    }

    @Override
    public void enviarNombreEstudiante() {
        String nombre;
        String usuario = fieldUsuario.getText();
        nombre = consulta.nombreApellidoEstudiante(usuario);
        estudiante.obtenerNombre(nombre);
    }

    @Override
    public void mostrarVentanaEstudiante(boolean b) {
        if (b == true) {
            iniciarInstanciaEstudiante.estudiante.setVisible(b);
        } else {
            iniciarInstanciaEstudiante.estudiante.setVisible(b);
        }
    }

    @Override
    public void enviarDatosProfesor() {
        String usuario;
        usuario = consulta.nombreProfesor();
        profesor.cargarNombre(usuario);
    }

    @Override
    public void mostrarVentanaProfesor(boolean b) {
        if (b == true) {
            iniciarInstanciaProfesor.profesor.setVisible(b);
        } else {
            iniciarInstanciaProfesor.profesor.setVisible(b);
        }

    }

    @Override
    public void enviarCursoMateria(String curso, String materia) {
    }

    @Override
    public void enviarEstudiantes(String nombre, String curso) {
    }

    @Override
    public void enviarCurso() {
        String curso = consulta.cursoEstudiante();
        String usuario = fieldUsuario.getText();
        estudiante.obtenerCurso(curso, usuario);
    }

    @Override
    public void enviarDatosTablaMateria(String materia, String curso) {
    }

    @Override
    public void enviarDatosTablaProfesor(String profesor, String curso) {
    }

    @Override
    public void enviarDatosTablaAula(String alumno, String curso) {
    }

    @Override
    public void enviarDatosEstudiante() {
    }

    @Override
    public void enviarProfesores(String nombre, String curso) {
    }

    @Override
    public void enviarTutores(String nombre, String nombreTutor, String curso) {
    }
}
